server:
  port: 8191

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AnujaKoralage/Rent-a-car-Config-Store
#          skipSslValidation: true
          search-paths:
          - 'service-config/*service'