server:
  port: 8191

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AnujaKoralage/Rent-a-Car/tree/master/git-config-store
          skipSslValidation: true
          search-paths:
            - '+service-config/*service'